---
version: '3.7'

services:

  app:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php56
    # Change container name for each project
    container_name: php_app
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - app_network
    volumes:
      - ./public_html:/var/www/html

  mysqldb:
    image: docker.io/library/mysql:8
    # Change container name for each project
    container_name: mysql_db
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - app_network
    volumes:
      - ./db_data:/var/lib/mysql
      - ./dockerfiles/my.cnf:/etc/mysql/my.cnf

volumes:
  public_html:
  db_data:

networks:
  app_network:
    driver: bridge
